# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

## Data Preprocessing

### Importing the dataset

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:

dataset = pd.read_excel('/content/drive/MyDrive/Deep Learning/ Combined Cycle Power Plant Data Set/Folds5x2_pp.xlsx', engine='openpyxl')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
dataset.shape

(9568, 5)

In [6]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

##  Building the ANN

### Initializing the ANN

In [8]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1))

##  Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 3s 3ms/step - loss: 162747.4062
Epoch 2/100
240/240 [==============================] - 1s 2ms/step - loss: 3185.0220
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 180.3484
Epoch 4/100
240/240 [==============================] - 1s 3ms/step - loss: 178.1989
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 175.8335
Epoch 6/100
240/240 [==============================] - 1s 3ms/step - loss: 173.0200
Epoch 7/100
240/240 [==============================] - 1s 3ms/step - loss: 169.8571
Epoch 8/100
240/240 [==============================] - 1s 3ms/step - loss: 166.2454
Epoch 9/100
240/240 [==============================] - 1s 2ms/step - loss: 162.0762
Epoch 10/100
240/240 [==============================] - 1s 3ms/step - loss: 157.6973
Epoch 11/100
240/240 [==============================] - 1s 5ms/step - loss: 152.6690
Epoch 12/100
240/240 [==============================] - 1s 4ms/step - 

### Predicting the results of the Test set

In [14]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 3ms/step
[[432.46 431.23]
 [463.82 460.01]
 [467.44 461.14]
 ...
 [474.48 473.26]
 [441.56 438.  ]
 [460.66 463.28]]
